version: "3.9"

services:

  database:
    image: postgres:13
    container_name: nest_db
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: willian
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    
  api:
    container_name: nest_api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/api
      - /home/api/node_modules
    
